export const colors = {
    baseRed: 'var(--baseRed)',
    baseWhite: 'var(--baseWhite)',
    ghostWhite: 'var(--ghostWhite)',
    successGreen: 'var(--successGreen)',
    secondaryGreen: 'var(--secondaryGreen)',
    coolGrey: 'var(--coolGrey)',
    lavenderGrey: 'var(--lavenderGrey)',
    ironGrey: 'var(--ironGrey)',
    ghostGrey: 'var(--ghostGrey)',
    tunaGrey: 'var(--tunaGrey)',
    mistGrey: 'var(--mistGrey)',
    silverGrey: 'var(--silverGrey)',
    boulderGrey: 'var(--boulderGrey)',
    aluminiumGrey: 'var(--aluminiumGrey)',
    shadowGrey: 'var(--shadowGrey)',
};
